/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";

const HELIX_SPEED = 6;

export function Airplane(props) {
  const spaceship = useGLTF("./models/airplane/spaceship_scifi.glb");
  console.log("spaceship", spaceship);

  const helix = useRef();

  useFrame((_state, delta) => {
    // helix.current.rotation.x += delta * HELIX_SPEED;
  });

  const position = [1, 0, 1];
  const rotation = [Math.PI / 2, -0.1, 0];
  const scale = [0.2, 0.2, 0.2];

  return (
    <group {...props} dispose={null}>
      <pointLight position={position} intensity={8} color="lightblue" />
      <mesh
        receiveShadow
        rotation={rotation}
        geometry={spaceship.nodes.Object_3.geometry}
        material={spaceship.materials}
        position={position}
        scale={scale}
      />

      <mesh
        geometry={spaceship.nodes.Object_3.geometry}
        position={position}
        rotation={rotation}
        scale={scale}
      >
        <meshStandardMaterial
          transparent
          opacity={1}
          color={"#a395e1"}
          intensity={100}
        />
      </mesh>
      <mesh
        geometry={spaceship.nodes.Object_2.geometry}
        position={position}
        rotation={rotation}
        scale={scale}
      >
        <meshStandardMaterial
          transparent
          opacity={1}
          color={"#6A5ACD"}
          intensity={100}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/airplane/model.glb");
