/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import {pointLight} from '@react-three/drei';

export function Cloud({ opacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/cloud/cloud_11.glb");
  console.log(nodes)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cloudball001.geometry}>
        <meshStandardMaterial
          {...materials["lambert2SG.001"]}
          transparent
          opacity={opacity}
          style={{filter:"blur(10px)"}}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/cloud/model.glb");
