/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 low_poly_stylized_planet.glb 
Author: twofiftyfive (https://sketchfab.com/twofiftyfive)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-stylized-planet-ca4b5384698747b1b805db33d2bbcdd2
Title: Low Poly Stylized Planet
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Plant01({ opacity, ...props }) {
  const { nodes, materials } = useGLTF(
    "./models/plants/low_poly_stylized_planet.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.moon_surface_flat}
            rotation={[0, -1.132, 0]}
            scale={11.976}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/plants/low_poly_stylized_planet.glb");
